name: e_health_monitoring_system_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.12.0
  dropdown_button2: ^2.3.9
  dart_jsonwebtoken: ^3.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  jwt_decode: ^0.3.1
  lottie: ^3.3.1
  provider: ^6.1.4
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-Thin.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic