name: e_health_monitoring_system_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-Thin.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 300  
          style: italic
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic